import {test,expect} from '@playwright/test';
test('loads demo, edits and reopens a saved draft without console errors',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();await page.getByLabel('Customer description',{exact:true}).fill('Edited specification');await page.getByRole('button',{name:'Save Demo'}).click();await expect(page.getByText('Demo draft saved for this preview session')).toBeVisible();await page.getByRole('button',{name:'Customer description preview'}).click();await expect(page.getByText('Edited specification')).toBeVisible();await expect(page.locator('.customer-preview')).not.toContainText('INTERNAL DEMO');expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)});
test('locked quote is read only; duplicate becomes separate draft',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/Locked issued example/}).click();await expect(page.getByRole('button',{name:'Save Demo'})).toBeDisabled();await expect(page.getByLabel('Quote reference',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Duplicate'}).click();await page.getByRole('button',{name:'Save Demo'}).click();await expect(page.getByText('Demo draft saved for this preview session')).toBeVisible();await expect(page.locator('.quote-list .quote')).toHaveCount(3)});
test('calculation requires explicit apply and keeps FX snapshot',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();await page.getByLabel('Product markup %',{exact:true}).fill('50');await expect(page.getByLabel('Saved product price AUD / unit',{exact:true})).toHaveValue('0.2015');await page.getByRole('button',{name:'Apply calculation'}).click();await expect(page.getByLabel('Saved product price AUD / unit',{exact:true})).toHaveValue('0.2325');await expect(page.getByLabel('FX · AUD per USD',{exact:true})).toHaveValue('1.5');await expect(page.getByLabel('Customer contact',{exact:true}).locator('option')).toHaveCount(2);await expect(page.getByLabel('Supplier contact',{exact:true}).locator('option')).toHaveCount(2)});

test('company selection populates contact and shipping details without stale values',async({page})=>{
 await page.goto('/');await page.getByLabel('Customer company',{exact:true}).selectOption('101');await expect(page.getByLabel('Customer contact',{exact:true})).toHaveValue('201');await expect(page.getByLabel('Email',{exact:true})).toHaveValue('customer@example.com');await expect(page.getByLabel('Shipping address',{exact:true})).toHaveValue('10 Example Street, Adelaide SA 5000, Australia');await page.getByLabel('Customer company',{exact:true}).selectOption('102');await expect(page.getByLabel('Email',{exact:true})).toHaveValue('');await expect(page.getByLabel('Shipping address',{exact:true})).toHaveValue('');
});
test('copy buttons copy exact edited descriptions and show calculated insurance in AUD',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async(text:string)=>{(window as unknown as {copiedText:string}).copiedText=text}}})});await page.goto('/');await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();await page.getByLabel('Customer description',{exact:true}).fill('Exact customer description');await page.getByRole('button',{name:'Copy customer description',exact:true}).click();expect(await page.evaluate(()=>(window as unknown as {copiedText:string}).copiedText)).toBe('Exact customer description');await page.getByLabel('Supplier description · Internal',{exact:true}).fill('Exact supplier description');await page.getByRole('button',{name:'Copy supplier description',exact:true}).click();expect(await page.evaluate(()=>(window as unknown as {copiedText:string}).copiedText)).toBe('Exact supplier description');await expect(page.getByLabel('Insurance USD',{exact:true})).toHaveValue('30');await expect(page.getByLabel('Insurance AUD',{exact:true})).toHaveValue('45.00');
});
