import {test,expect} from '@playwright/test';
test('loads demo, edits and reopens a saved draft without console errors',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();await page.getByLabel('Customer description',{exact:true}).fill('Edited specification');await page.getByRole('button',{name:'Save Demo'}).click();await expect(page.getByText('Demo draft saved for this preview session')).toBeVisible();await page.getByRole('button',{name:'Customer description preview'}).click();await expect(page.getByText('Edited specification')).toBeVisible();await expect(page.locator('.customer-preview')).not.toContainText('INTERNAL DEMO');expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)});
test('locked quote is read only; duplicate becomes separate draft',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/Locked issued example/}).click();await expect(page.getByRole('button',{name:'Save Demo'})).toBeDisabled();await expect(page.getByLabel('Quote reference',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Duplicate'}).click();await page.getByRole('button',{name:'Save Demo'}).click();await expect(page.getByText('Demo draft saved for this preview session')).toBeVisible();await expect(page.locator('.quote-list .quote')).toHaveCount(3)});
test('calculation requires explicit apply and keeps FX snapshot',async({page})=>{await page.goto('/');await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();await page.getByLabel('Markup %',{exact:true}).fill('50');await expect(page.getByLabel('Saved product price AUD / unit',{exact:true})).toHaveValue('$0.2015');await page.getByRole('button',{name:'Re-calculate'}).click();await expect(page.getByLabel('Saved product price AUD / unit',{exact:true})).toHaveValue('$0.2325');await expect(page.getByLabel('Exchange Rate',{exact:true})).toHaveValue('1.5');await expect(page.getByLabel('Customer contact',{exact:true}).locator('option')).toHaveCount(2);await expect(page.getByLabel('Supplier contact',{exact:true}).locator('option')).toHaveCount(2)});

test('company selection populates contact and shipping details without stale values',async({page})=>{
 await page.goto('/');await page.getByLabel('Customer company',{exact:true}).selectOption('101');await expect(page.getByLabel('Customer contact',{exact:true})).toHaveValue('201');await expect(page.getByLabel('Email',{exact:true})).toHaveValue('customer@example.com');await expect(page.getByLabel('Shipping address',{exact:true})).toHaveValue('10 Example Street, Adelaide SA 5000, Australia');await page.getByLabel('Customer company',{exact:true}).selectOption('102');await expect(page.getByLabel('Email',{exact:true})).toHaveValue('');await expect(page.getByLabel('Shipping address',{exact:true})).toHaveValue('');
});
test('copy buttons copy exact edited descriptions and show calculated insurance in AUD',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async(text:string)=>{(window as unknown as {copiedText:string}).copiedText=text}}})});await page.goto('/');await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();await page.getByLabel('Customer description',{exact:true}).fill('Exact customer description');await page.getByRole('button',{name:'Copy customer description',exact:true}).click();expect(await page.evaluate(()=>(window as unknown as {copiedText:string}).copiedText)).toBe('Exact customer description');await page.getByLabel('Supplier description · Internal',{exact:true}).fill('Exact supplier description');await page.getByRole('button',{name:'Copy supplier description',exact:true}).click();expect(await page.evaluate(()=>(window as unknown as {copiedText:string}).copiedText)).toBe('Exact supplier description');await expect(page.getByLabel('Insurance USD',{exact:true})).toHaveValue('$30.00');await expect(page.getByLabel('Insurance AUD',{exact:true})).toHaveValue('$45.00');
});

test('undo, redo and discard restore draft edits and saving clears edit history',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();await page.getByLabel('Customer description',{exact:true}).fill('Changed once');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('Customer description',{exact:true})).toHaveValue('Demo packaging · 300 × 400 mm · white · 10,000 units');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.getByLabel('Customer description',{exact:true})).toHaveValue('Changed once');await page.getByRole('button',{name:'Discard',exact:true}).click();await expect(page.getByLabel('Customer description',{exact:true})).toHaveValue('Demo packaging · 300 × 400 mm · white · 10,000 units');await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();await page.getByLabel('Customer description',{exact:true}).fill('Saved edit');await page.getByRole('button',{name:'Save Demo',exact:true}).click();await expect(page.getByText('Demo draft saved for this preview session')).toBeVisible();await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Discard',exact:true})).toBeDisabled();
});
test('Update descriptions applies current country and thickness rules and can be undone',async({page})=>{
 page.on('dialog',d=>d.accept());await page.goto('/');await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();await page.getByRole('button',{name:'Update customer description',exact:true}).click();await expect(page.getByLabel('Customer description',{exact:true})).toHaveValue(/AS 5810 certified/);await page.getByLabel('Thickness (microns)',{exact:true}).fill('80');await page.getByRole('button',{name:'Update supplier description',exact:true}).click();await expect(page.getByLabel('Supplier description · Internal',{exact:true})).toHaveValue(/AS 4736 certified/);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('Supplier description · Internal',{exact:true})).toHaveValue('INTERNAL DEMO supplier specification');
});

test('incomplete drafts keep all calculated totals and green summary visible',async({page})=>{
 await page.goto('/');
 const totals=page.locator('.calculation-totals input');await expect(totals).toHaveCount(9);
 for(const input of await totals.all()){await expect(input).toBeVisible();await expect(input).toHaveValue('—');}
 await expect(page.getByLabel('Cost summary',{exact:true})).toBeVisible();await expect(page.locator('.cost-summary b')).toHaveText(['—','—','—','—']);
 await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();await expect(page.getByLabel('Total USD',{exact:true})).toHaveValue('$1,000.00');await expect(page.locator('.cost-summary')).toContainText('$1,550.00');
 await page.getByLabel('Exchange Rate',{exact:true}).fill('');await expect(totals).toHaveCount(9);await expect(page.getByLabel('Total USD',{exact:true})).toHaveValue('—');await expect(page.getByLabel('Cost summary',{exact:true})).toBeVisible();
});

test('currency inputs format on blur while raw decimals and saved FX remain editable',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();
 const unit=page.getByLabel('Supplier USD / unit',{exact:true});await expect(unit).toHaveValue('$0.1000');await unit.focus();await expect(unit).toHaveValue('0.10');await unit.fill('0.123456');await page.getByRole('heading',{name:'Packaging',exact:true}).click();await expect(unit).toHaveValue('$0.1235');await unit.focus();await expect(unit).toHaveValue('0.123456');
 const bank=page.getByLabel('Bank fees USD',{exact:true});await bank.fill('$1,234.50');await page.getByRole('button',{name:'Save Demo'}).click();await expect(page.getByText('Demo draft saved for this preview session')).toBeVisible();await expect(bank).toHaveValue('$1,234.50');await bank.focus();await expect(bank).toHaveValue('1234.50');await unit.focus();await expect(unit).toHaveValue('0.123456');await expect(page.getByLabel('Exchange Rate',{exact:true})).toHaveValue('1.5');
});

test('numeric quantities show grouping and preserve raw values through saving',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:/TEST — Demo packaging quote/}).click();const quantity=page.getByLabel('Supplier quantity',{exact:true});await expect(quantity).toHaveValue('10,000');await quantity.focus();await expect(quantity).toHaveValue('10000');await quantity.fill('12,345');await page.getByRole('button',{name:'Save Demo'}).click();await expect(page.getByText('Demo draft saved for this preview session')).toBeVisible();await expect(quantity).toHaveValue('12,345');await quantity.focus();await expect(quantity).toHaveValue('12345');await expect(page.getByLabel('Exchange Rate',{exact:true})).toHaveValue('1.5');await expect(page.getByLabel('Sell Incl Shipping AUD',{exact:true})).toHaveValue('$0.2006');
});
